"""Content-type-specific rendering for ChatGPT message parts."""

from __future__ import annotations

from .models import ContentPart, ContentType


def render_content(raw_content: dict) -> list[ContentPart]:
    """Dispatch on content_type to produce ContentPart objects.

    Handles all known ChatGPT content types with graceful fallback for unknowns.
    """
    content_type = raw_content.get("content_type", "text")

    handler = _HANDLERS.get(content_type, _handle_unknown)
    return handler(raw_content)


def _handle_text(content: dict) -> list[ContentPart]:
    """Standard text content — the most common type."""
    parts = content.get("parts", [])
    result = []
    for part in parts:
        if isinstance(part, str) and part.strip():
            result.append(ContentPart(content_type=ContentType.TEXT, text=part))
        elif isinstance(part, dict):
            result.extend(_handle_structured_part(part))
    return result


def _handle_multimodal_text(content: dict) -> list[ContentPart]:
    """Text interleaved with images and other media."""
    parts = content.get("parts", [])
    result = []
    for part in parts:
        if isinstance(part, str) and part.strip():
            result.append(ContentPart(content_type=ContentType.TEXT, text=part))
        elif isinstance(part, dict):
            result.extend(_handle_structured_part(part))
    return result


def _handle_structured_part(part: dict) -> list[ContentPart]:
    """Handle a single structured part (image, file, etc.)."""
    ct = part.get("content_type", "")

    if "image" in ct:
        pointer = part.get("asset_pointer", "")
        return [ContentPart(
            content_type=ContentType.TEXT,
            text=f"[Image: {pointer}]" if pointer else "[Image]",
            image_ref=pointer or None,
        )]

    if ct == "file" or "file" in ct:
        name = part.get("name", "unnamed_file")
        return [ContentPart(content_type=ContentType.TEXT, text=f"[File: {name}]")]

    if "text" in part and part["text"]:
        return [ContentPart(content_type=ContentType.TEXT, text=part["text"])]

    return []


def _handle_code(content: dict) -> list[ContentPart]:
    """Code generated by Code Interpreter / Advanced Data Analysis."""
    code_text = content.get("text", "")
    language = content.get("language", "python")
    return [ContentPart(
        content_type=ContentType.CODE,
        text=code_text,
        language=language,
    )]


def _handle_execution_output(content: dict) -> list[ContentPart]:
    """Output from Code Interpreter execution."""
    output = content.get("text", "")
    if not output:
        return []
    return [ContentPart(
        content_type=ContentType.EXECUTION_OUTPUT,
        text=output,
    )]


def _handle_browsing_display(content: dict) -> list[ContentPart]:
    """Web browsing results summary."""
    result_text = content.get("result", "")
    if not result_text:
        return []
    return [ContentPart(
        content_type=ContentType.BROWSING_DISPLAY,
        text=result_text,
    )]


def _handle_browsing_quote(content: dict) -> list[ContentPart]:
    """Quoted text from web browsing."""
    title = content.get("title", "")
    text = content.get("text", "")
    url = content.get("url", "")
    return [ContentPart(
        content_type=ContentType.BROWSING_QUOTE,
        text=text,
        title=title,
        url=url,
    )]


def _handle_unknown(content: dict) -> list[ContentPart]:
    """Fallback for unrecognized content types."""
    # Try to extract whatever text we can
    parts = content.get("parts", [])
    text = content.get("text", "")
    ct_name = content.get("content_type", "unknown")

    result = []
    if text:
        result.append(ContentPart(content_type=ContentType.UNKNOWN, text=text))
    elif parts:
        for part in parts:
            if isinstance(part, str) and part.strip():
                result.append(ContentPart(content_type=ContentType.UNKNOWN, text=part))

    if not result:
        result.append(ContentPart(
            content_type=ContentType.UNKNOWN,
            text=f"[Unsupported content type: {ct_name}]",
        ))

    return result


# Content type dispatch table
_HANDLERS = {
    "text": _handle_text,
    "code": _handle_code,
    "execution_output": _handle_execution_output,
    "tether_browsing_display": _handle_browsing_display,
    "tether_quote": _handle_browsing_quote,
    "multimodal_text": _handle_multimodal_text,
}
